image: microsoft/dotnet:latest

stages:
  - build
  - test

variables:
  test: "UnitTestClient"

  before_script:
    - "cd src"
    - "dotnet resetore"

build:
  stage: build
  script: "dotnet build"

test:
  stage: test
  script:
    - "cd $test"
    - "dotnet test"